name: app_db
description: Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:    # 日历弹窗必需
    sdk: flutter
  shared_preferences: ^2.2.2  # 本地存储
  http: ^1.2.0                # 网络请求
  provider: ^6.1.2            # 状态管理
  intl: any                   # 日期格式化

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true